mysql:
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: true
  log-zap: ""
  prefix: 'xc'
  path: '127.0.0.1:3306'
  db-name: 'inscribe'
  username: 'root'
  password: '123456'
zap:
  level: 'info'
  format: 'console'
  prefix: ''
  director: 'log'
  link-name: 'log/latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true
